# Generated by Django 5.0.1 on 2024-02-11 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=2048)),
                ('doc_id', models.CharField(max_length=2048, null=True)),
                ('type', models.CharField(choices=[('website', 'Website'), ('pdf', 'PDF'), ('plain_text', 'Plain Text')], max_length=255)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('content', models.TextField(null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('keywords', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_base_documents',
                'unique_together': {('user_id', 'identifier')},
            },
        ),
    ]
