# Generated by Django 5.0.1 on 2024-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('identifier', models.CharField(max_length=2048, unique=True)),
                ('doc_id', models.CharField(max_length=2048, null=True)),
                ('type', models.CharField(choices=[('website', 'Website'), ('pdf', 'Pdf'), ('plain_text', 'Plain Text')], max_length=255)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'db_table': 'knowledge_base_documents',
            },
        ),
    ]
