# Generated by Django 5.0.1 on 2024-02-19 14:48

import knowledge_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=knowledge_base.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("pdf", "PDF"),
                    ("plain_text", "Plain Text"),
                    ("word", "Word"),
                ],
                max_length=255,
            ),
        ),
    ]
