# Generated by Django 5.0.1 on 2024-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0002_document_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="keywords",
            field=models.TextField(null=True),
        ),
    ]
