# Generated by Django 5.1.6 on 2025-02-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_alter_document_file_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('PDF', 'PDF'), ('PLAIN_TEXT', 'Plain Text'), ('WORD', 'Word')], max_length=255),
        ),
    ]
