# Generated by Django 5.0.1 on 2024-02-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0003_document_keywords_document_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="documents/"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="url",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
