# Generated by Django 5.0.1 on 2024-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0004_document_file_document_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("pdf", "PDF"),
                    ("plain_text", "Plain Text"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
