# Generated by Django 5.0.1 on 2024-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="source_documents",
            field=models.ManyToManyField(
                related_name="messages", to="knowledge_base.document"
            ),
        ),
    ]
