# Generated by Django 5.0.1 on 2024-02-15 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageSourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("excerpt", models.TextField(blank=True, default=None, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge_base.document",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "db_table": "conversations_message_source_document",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="source_documents",
            field=models.ManyToManyField(
                through="conversations.MessageSourceDocument",
                to="knowledge_base.document",
            ),
        ),
    ]
