# Generated by Django 5.1.6 on 2025-02-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_messagesourcedocument_message_source_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesourcedocument',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='messagesourcedocument',
            name='end_char_idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagesourcedocument',
            name='start_char_idx',
            field=models.IntegerField(default=0),
        ),
    ]
