# Generated by Django 5.0.1 on 2024-02-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_status_conversation_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="COMPLETED",
                max_length=10,
            ),
        ),
    ]
