# Generated by Django 5.0.1 on 2024-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retrieval", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="doc_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
